Compile fixes
 commit 917a33379258c137324cb9204e2f2f6ed8dc2b78

Bluetooth: btusb: Change 1 to true in bool type variable assignment

The reset is a bool type variable. So assigning true to reset instead
of 1.

Signed-off-by: Shailendra Verma <shailendra.capricorn@gmail.com>
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

---------------------------------------------------------

 commit 9ff158f4c245c2fecb1489a4aae62ca67c0846a1

usb: phy: fix dual role sysfs build if kernel modules are supported

Add a missing ";" after EXPORT_SYMBOL() otherwise we run
into following build error if Kernel Modules are supported:
----------
  CC      drivers/usb/phy/class-dual-role.o
drivers/usb/phy/class-dual-role.c:91:1: error: expected ',' or ';' before 'int'
 int dual_role_get_property(struct dual_role_phy_instance *dual_role,
 ^
make[3]: *** [drivers/usb/phy/class-dual-role.o] Error 1
----------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

--------------------------------------------------------

Bullhead_defconfig: Enable CONFIG_BT_ATH3K
mm: filemap.c: Fix export_symbol func. name according to 2405316c4fd50d8fbe923d96a8ab09e80f622a60